magnum-web-main/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")

     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="Events")
     * @ORM\JoinColumn(nullable=false)

     */
    private $User;

    /**
     * @Assert\NotBlank(message="Name cannot be empty")
     * @Assert\NotNull(message="Name cannot be Null")
     * @ORM\Column(type="string", length=255)

     */
    private $Name;

    /**
     * @Assert\NotBlank(message="Description cannot be empty")
     * @Assert\NotNull(message="Description cannot be Null")
     * @ORM\Column(type="string", length=255)

     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)

     */
    private $Type;

    /**
     * @Assert\NotBlank(message="Location cannot be empty")
     * @Assert\NotNull(message="Location cannot be Null")
     * @ORM\Column(type="string", length=255, nullable=true)

     */
    private $Location;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today",message="Cannot Pick Date < Today's Date")

     */
    private $Date;

    /**
     * @ORM\Column(type="boolean")

     */
    private $Payant;

    /**
     * @Assert\NotBlank(message="Price cannot be empty")
     * @Assert\NotNull(message="Price cannot be Null")
     * @Assert\Positive(message="Price cannot be Negative")
     * @ORM\Column(type="float")

     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)

     */
    private $Status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="Event",cascade={"remove"})

     */
    private $Reviews;

    /**
     * @ORM\ManyToMany(targetEntity=Users::class)
     * @ORM\JoinTable(name="user_event",
     *      joinColumns={ @ORM\JoinColumn(name="event_id", referencedColumnName="id") },
     *      inverseJoinColumns={ @ORM\JoinColumn(name="user_id", referencedColumnName="id") })


     */
    private $Participants;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Max Participants cannot be empty")
     * @Assert\NotNull(message="Max Participants cannot be Null")
     * @Assert\Positive(message="Max Participants cannot be Negative")

     */
    private $MaxParticipants;

    public function __construct()
    {
        $this->Reviews = new ArrayCollection();
        $this->Participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->User;
    }

    public function setUser(?Users $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getPayant(): ?bool
    {
        return $this->Payant;
    }

    public function setPayant(bool $Payant): self
    {
        $this->Payant = $Payant;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): ?Collection
    {
        return $this->Reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->Reviews->contains($review)) {
            $this->Reviews[] = $review;
            $review->setEvent($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->Reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getEvent() === $this) {
                $review->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getParticipants(): ?Collection
    {
        return $this->Participants;
    }

    public function addParticipant(Users $participant): self
    {
        if (!$this->Participants->contains($participant)) {
            $this->Participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(Users $participant): self
    {
        $this->Participants->removeElement($participant);

        return $this;
    }

    public function getMaxParticipants(): ?int
    {
        return $this->MaxParticipants;
    }

    public function setMaxParticipants(int $MaxParticipants): self
    {
        $this->MaxParticipants = $MaxParticipants;

        return $this;
    }
}

magnum-web-main/src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType; 
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
       ;
        
    }   

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

magnum-web-main/templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello OrderController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/asus/Magnum-website/src/Controller/OrderController.php'|file_link(0) }}">src/Controller/OrderController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/asus/Magnum-website/templates/order/index.html.twig'|file_link(0) }}">templates/order/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

magnum-web-main/templates/order/pdf.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style type="text/css">
    @font-face {
  font-family: Junge;
  src: url(Junge-Regular.ttf);
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  color: #001028;
  text-decoration: none;
}

body {
  font-family: Junge;
  position: relative;
  width: 21cm;  
  height: 29.7cm; 
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-size: 14px; 
}

.arrow {
  margin-bottom: 4px;
}

.arrow.back {
  text-align: right;
}

.inner-arrow {
  padding-right: 10px;
  height: 30px;
  display: inline-block;
  background-color: rgb(233, 125, 49);
  text-align: center;

  line-height: 30px;
  vertical-align: middle;
}

.arrow.back .inner-arrow {
  background-color: rgb(233, 217, 49);
  padding-right: 0;
  padding-left: 10px;
}

.arrow:before,
.arrow:after {
  content:'';
  display: inline-block;
  width: 0; height: 0;
  border: 15px solid transparent;
  vertical-align: middle;
}

.arrow:before {
  border-top-color: rgb(233, 125, 49);
  border-bottom-color: rgb(233, 125, 49);
  border-right-color: rgb(233, 125, 49);
}

.arrow.back:before {
  border-top-color: transparent;
  border-bottom-color: transparent;
  border-right-color: rgb(233, 217, 49);
  border-left-color: transparent;
}

.arrow:after {
  border-left-color: rgb(233, 125, 49);
}

.arrow.back:after {
  border-left-color: rgb(233, 217, 49);
  border-top-color: rgb(233, 217, 49);
  border-bottom-color: rgb(233, 217, 49);
  border-right-color: transparent;
}

.arrow span { 
  display: inline-block;
  width: 80px; 
  margin-right: 20px;
  text-align: right; 
}

.arrow.back span { 
  margin-right: 0;
  margin-left: 20px;
  text-align: left; 
}

h1 {
  color: #5D6975;
  font-family: Junge;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  border-top: 1px solid #5D6975;
  border-bottom: 1px solid #5D6975;
  margin: 0 0 2em 0;
}

h1 small { 
  font-size: 0.45em;
  line-height: 1.5em;
  float: left;
} 

h1 small:last-child { 
  float: right;
} 

#project { 
  float: left; 
}

#company { 
  float: right; 
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 30px;
}

table th,
table td {
  text-align: center;
}

table th {
  padding: 5px 20px;
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
  padding: 20px;
  text-align: right;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.sub {
  border-top: 1px solid #C1CED9;
}

table td.grand {
  border-top: 1px solid #5D6975;
}

table tr:nth-child(2n-1) td {
  background: #EEEEEE;
}

table tr:last-child td {
  background: #DDDDDD;
}

#details {
  margin-bottom: 30px;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}
    </style>
  </head>
  <body>
    <main>
      <h1 class="clearfix"><small><span></span><br /></small>Orders list<small><span></span><br /></small></h1>
      <table>
        <thead>
          <tr>
            <th class="service">Offer</th>
            <th class="desc">User</th>
            <th>Plan</th>
            <th>Total</th>
            <th>Order date</th>
            <th>Status</th>
          </tr>
        </thead>
                        
        <tbody>
        {% for ors in orderlist %}
          <tr>
            <td class="service"><img width="30px" height="30px" src="img/ofs-img/{{ors.Offer.image}}" alt=""></td>
            <td class="desc">{{ ors.User.username }}</td>
            <td class="unit">{{ ors.plan }}</td>
            <td class="qty">${{ ors.total }}</td>
            <td class="total">{{ ors.orderdate }}</td>
            <td class="total">{{ ors.status }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div id="details" class="clearfix">
        <div id="project">
          <div class="arrow"><div class="inner-arrow"><span>PROJECT</span> Podcasting website</div></div>
          <div class="arrow"><div class="inner-arrow"><span>EMAIL</span> <a href="mailto:john@example.com">	devel.magnum@gmail.com</a></div></div>
        </div>
        <div id="company">
          <div class="arrow back"><div class="inner-arrow">Magnum Team<span>COMPANY</span></div></div>
          <div class="arrow back"><div class="inner-arrow">+216 53120008<span>PHONE</span></div></div>
        </div>
      </div>
      
    </main>
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>